---
- name: Create a simple webserver
  hosts: terraform-ansible
  tasks:
    - name: Create index file
      copy:
        dest: /home/ubuntu/index.html
        content: <h1>Made with terraform and Ansible</h1>
    - name: Create Server
      shell: "nohup busybox httpd -f -p 8080 &"
