---
- name: Installing python in instance
  hosts: terraform-ansible
  tasks:
    - name: Install python3 and virtualenv
      apt:
        pkg:
          - python3
          - virtualenv
        update_cache: true
      become: true
    - name: Instalando dependencias com pip
      ansible.builtin.pip:
        virtualenv: /home/ubuntu/venv
        name:
          - django
          - djangorestframework
    - name: Iniciando o projeto
      ansible.builtin.shell: '. /home/ubuntu/venv/bin/activate; django-admin startproject setup /home/ubuntu/'
    - name: Alterando o hosts do settings
      lineinfile:
        path: /home/ubuntu/setup/settings.py'
        regexp: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: true

