---
- name: Installing python in instance
  hosts: terraform-ansible
  tasks:
    - name: Install python3 and virtualenv
      apt:
        pkg:
        - python3
        - virtualenv
        update_cache: yes
      become: yes
    - name: Instalando dependencias com pip
      pip:
        virtualenv: /home/ubuntu/venv
        name:
          - django
          - djangorestframework

    - name: Check if project already exist
      stat:
        path: /home/ubuntu/setup/settings.py
      register: project

    - name: Start project
      shell: '. /home/ubuntu/venv/bin/activate; django-admin startproject setup /home/ubuntu/'
      when: not project.stat.exists
      # ignore_errors: yes

    - name: Changing hosts from settings
      lineinfile:
        path: /home/ubuntu/setup/settings.py
        regexp: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes

